### ISSUE TITLE
The binaries can't handle the message arg starting with a symbol

### ISSUE THREAD

**Issue by dynamicdan** [chbrown/osx-notifier#1]
Eg, terminal-notifier-info.app running:
`./terminal-notifier-info.app/Contents/MacOS/terminal-notifier -message "(tesing) - something"`
Causes error.

These work:
./terminal-notifier-info.app/Contents/MacOS/terminal-notifier -message "_(tesing) - something"
./terminal-notifier-info.app/Contents/MacOS/terminal-notifier -message "tesing) - something"

How can we fix this? I have a workaround in my app atm that appends '_' when required.

**Comment by chbrown** [comment]
Interesting bug. It boils down to how OS X Foundation handles command line arguments in the `[NSUserDefaults standardUserDefaults]` call in the [`terminal-notifier/AppDelegate.m`](https://github.com/julienXX/terminal-notifier/blob/878042f5/Terminal%20Notifier/AppDelegate.m#L57) app. You can also test this out really easily with a Swift script. `echo-message.swift`:

```
import Foundation
print(NSUserDefaults.standardUserDefaults().objectForKey("message"))
```

Run `swift echo-message.swift -message 'Hello there'` and compare to `swift echo-message.swift -message '(Hello) there'`.

It pretty much just swallows all quotes: 

```
$ swift echo-message.swift -message Hello
Optional(Hello)
$ swift echo-message.swift -message "Hello"
Optional(Hello)
$ swift echo-message.swift -message '"Hello"'
Optional(Hello)
$ swift echo-message.swift -message ""Hello""
Optional(Hello)
$ swift echo-message.swift -message """Hello"""
Optional(Hello)
```

The problem in your case is that it was trying to evaluate the argument as a tuple, due to the objectForKey call in terminal-notifier, which failed after encountering data after the tuple. stringForKey doesn't fare any better, btw.

Perplexing behavior on OS X's part, but easy to deal with.

The solution is to escape all quotes and wrap each argument in quotes, which is implemented in 50188ba / `v0.2.2` (just now published to [NPM registry](https://www.npmjs.com/package/osx-notifier)).
